### ISSUE TITLE
Links at bottom

### ISSUE THREAD

**Issue by vanslykej** [hornbergerc/hornbergerc.github.io#1]
The links at the bottom of the site which lead to Twitter, Facebook, Mail, etc. do not lead to your specific accounts. You can change this in the _config.yml file and either putting in your user name for these
accounts or deleting it all together depending which ones you want or have. Make sure if you do put your user name for example say, Twitter, to change the value for Twitter underneath this section to true and any account that you don't want to say false.

**Comment by hornbergerc** [comment]
I will change those, I was in the middle of the steps for deleting them.

**Comment by zbzoll** [comment]
when you deleted the links at the bottom you accidentally deleted the git hub server link.

**Comment by hornbergerc** [comment]
I fixed that, thank you.
