### ISSUE TITLE
Closing Tags

### ISSUE THREAD

**Issue by Nikki-Luoma** [hornbergerc/hornbergerc.github.io#14]
You should add <small> to the beginning of the photo credits, this will cause the writing to be smaller. 
<small> piracy flickr photo by robotson shared under a Creative Commons (BY-NC) license </small>
<small> cd flickr photo by Dean Hochman shared under a Creative Commons (BY) license </small>

**Comment by hornbergerc** [comment]
What do you mean?

**Comment by hornbergerc** [comment]
I figured it out and I made the changes, thank you.
