### ISSUE TITLE
Possible Word Change

### ISSUE THREAD

**Issue by Nikki-Luoma** [hornbergerc/hornbergerc.github.io#6]
"The answer that people find will be to look at their phones or GPS." possibly change this to "Most people would answer this question by looking at their phones or their GPS."

**Comment by Nikki-Luoma** [comment]
"Roads are under construction or are always changing, and the mapping service is not up-to-date." possibly change to, "Sometimes roads are under construction and are constantly changing, and the mapping services are not always up-to-date."

**Comment by Nikki-Luoma** [comment]
"The stress of being places and then not knowing how to get to a location is a lot for someone to handle." This sentence is a little bit confusing.

**Comment by Nikki-Luoma** [comment]
'was “I’ll plug in my phone to a charger, and I’ll be set and.”' I do not think that the 'and' should be there.

**Comment by hornbergerc** [comment]
I fixed those changes, thank you.
