### ISSUE TITLE
Piracy issues

### ISSUE THREAD

**Issue by zbzoll** [hornbergerc/hornbergerc.github.io#9]
starting a new issue tracker

**Comment by zbzoll** [comment]
I like the way you concluded your issue but I suggest that you should add more on to your conclusion by adding some of your own opinions into the article. Your title is kinda plan try to add more spice to it if you can

**Comment by hornbergerc** [comment]
Thank you, I will add more to the conclusion.

**Comment by zbzoll** [comment]
your welcome
